export let nav=[
    {
        path:"/",
        name:'Dashboard',
    },
    {
        path:"/users",
        name:'Users',
    },
    {
        path:"/product",
        name:'Product'
    },
    {
        path:"/about",
        name:'About'
    },
    {
        path:"/contact",
        name:'Contact'
    }
]